ci: Organize CI to test changes in Sentry
- splits uploads in 2 different parts, with one special case to test ATS
- ATS setup to generate tests to run and to skip

diff --git a/.github/workflows/iterative_testing.yml b/.github/workflows/iterative_testing.yml
--- a/.github/workflows/iterative_testing.yml
+++ b/.github/workflows/iterative_testing.yml
@@ -1,53 +1,96 @@
 name: smart test selection
 
-on: [push]
+on:
+  pull_request:
 
 jobs:
-  # install-codecov-cli:
-  #   uses: ./.github/workflows/download_cli.yml
-  static-analysis:
-    # needs: install-codecov-cli
+
+  coverage-ats:
     runs-on: ubuntu-latest
+    # Map a step output to a job output
+    outputs:
+      ATS_TESTS_TO_RUN: ${{ steps.label_analysis.outputs.ATS_TESTS_TO_RUN }}
+      ATS_TESTS_TO_SKIP: ${{ steps.label_analysis.outputs.ATS_TESTS_TO_SKIP }}
     steps:
-      - uses: actions/checkout@v3
-      - name: Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.10.10"
-      - name: Install Codecov CLI from pip
-        run: |
-          pip install pytest codecov-cli
-      - name: Save commit info 
-        run: |
-          codecovcli create-commit --git-service=github --token=${{ secrets.CODECOV_TOKEN }}
-      - name: Create report
-        run: |
-          codecovcli create-report --git-service=github --token=${{ secrets.CODECOV_TOKEN }}
-      - name: Run Static Analysis
-        run: |
-          codecovcli static-analysis --token=${{ secrets.STATIC_TOKEN }}
-  iterative-testing:
-    needs: static-analysis
+    - uses: actions/checkout@v3
+      with:
+        fetch-depth: 2
+    - name: Set up Python 3.10.10
+      uses: actions/setup-python@v4
+      with:
+        python-version: "3.10.10"
+    # We need the setup to collect the list of tests properly
+    - name: Setup sentry env
+      uses: ./.github/actions/setup-sentry
+      id: setup
+      with:
+        snuba: true
+        # Right now, we run so few bigtable related tests that the
+        # overhead of running bigtable in all backend tests
+        # is way smaller than the time it would take to run in its own job.
+        bigtable: true
+        pg-version: 14
+    - name: Download Codecov CLI
+      run: |
+        pip install --extra-index-url https://pypi.org/simple --no-cache-dir codecov-cli
+    # Creates the commit and report objects in codecov
+    - name: Codecov startup
+      run: |
+        codecovcli create-commit
+        codecovcli create-report
+      env:
+        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+    # Sends static analysis information to codecov
+    - name: Static Analysis
+      run: |
+        codecovcli static-analysis --token=${CODECOV_STATIC_TOKEN} \
+        --folders-to-exclude .artifacts \
+        --folders-to-exclude .github \
+        --folders-to-exclude .venv \
+        --folders-to-exclude static \
+        --folders-to-exclude bin
+      env:
+        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+        CODECOV_STATIC_TOKEN: ${{ secrets.STATIC_TOKEN }}
+    # Run label analysis in dry mode to get the list of tests to run
+    # The base commit will be the parent commit (apparently commits on master don't exist in codecov)
+    - name: Label Analysis
+      id: label_analysis
+      continue-on-error: true
+      run: |
+        set +e
+        BASE_COMMIT=$(git rev-parse ${{ github.sha }}^)
+        echo $BASE_COMMIT
+        output=$(codecovcli --codecov-yml-path=codecov.yml label-analysis --dry-run --token=${CODECOV_STATIC_TOKEN} --base-sha=${BASE_COMMIT})
+        if [ $? -eq 0 ]
+        then
+          ATS_TESTS_TO_RUN=$(echo $output | grep -e ATS_TESTS_TO_RUN= | tr -d "ATS_TESTS_TO_RUN=")
+          ATS_TESTS_TO_SKIP=$(echo $output | grep -e ATS_TESTS_TO_SKIP= | tr -d "ATS_TESTS_TO_SKIP=")
+
+          echo "ATS_TESTS_TO_RUN=$ATS_TESTS_TO_RUN" >> "$GITHUB_OUTPUT"
+          echo "ATS_TESTS_TO_SKIP=$ATS_TESTS_TO_SKIP" >> "$GITHUB_OUTPUT"
+
+          test_to_run_count=$(echo $ATS_TESTS_TO_RUN | awk '{print gsub("[ \t]",""); exit}')
+          test_to_skip_count=$(echo $ATS_TESTS_TO_SKIP | awk '{print gsub("[ \t]",""); exit}')
+          echo "Selected $test_to_run_count / $total_tests_count tests to run" >> $GITHUB_STEP_SUMMARY
+        else
+          echo "ATS failed. Can't get list of tests to run. Fallback to all tests"
+          echo "ATS failed. Can't get list of tests to run. Fallback to all tests" >> $GITHUB_STEP_SUMMARY
+          echo "ATS_TESTS_TO_RUN=--cov-context=test" >> "$GITHUB_OUTPUT"
+          echo "ATS_TESTS_TO_SKIP=" >> "$GITHUB_OUTPUT"
+        fi
+
+      env:
+        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+        CODECOV_STATIC_TOKEN: ${{ secrets.STATIC_TOKEN }}
+  debug:
     runs-on: ubuntu-latest
+    needs: coverage-ats
     steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - name: Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.10.10"
-      - name: Install Pytest and its dependencies
+      - name: Debug ATS_TESTS_TO_RUN
         run: |
-          pip install pytest pytest-cov pytest-mock
-      - name: Install Codecov CLI from pip
+          echo ${{ needs.coverage-ats.outputs.ATS_TESTS_TO_RUN }}
+      - name: Debug ATS_TESTS_TO_SKIP
         run: |
-          pip install codecov-cli
-      - name: Run smart test selection
-        run: |
-          BASE_COMMIT=$(git merge-base ${{ github.sha }}^ origin/main)
-          echo "Using base commit ${BASE_COMMIT}"
-          codecovcli label-analysis --token=${{ secrets.STATIC_TOKEN }} --base-sha=${BASE_COMMIT}
-          coverage json --show-contexts -o label.coverage.json
-          rm .coverage
-          codecovcli --verbose do-upload --flag smart-tests --file=label.coverage.json --token=${{ secrets.CODECOV_TOKEN }}  --fail-on-error
+          echo ${{ needs.coverage-ats.outputs.ATS_TESTS_TO_SKIP }}
+          
